FASHION = 'FASHION'
FOOTWEAR = 'FOOTWEAR'
GROCERY = 'GROCERY'
ELECTRONICS = 'ELECTRONICS'
STATIONERY = 'STATIONERY'

PRODUCT_CATEGORY = [
    (FASHION, 'FASHION'),
    (FOOTWEAR, 'FOOTWEAR'),
    (GROCERY, 'GROCERY'),
    (ELECTRONICS, 'ELECTRONICS'),
    (STATIONERY, 'STATIONERY'),
]
