# Generated by Django 3.2.12 on 2023-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FASHION', 'FASHION'), ('FOOTWEAR', 'FOOTWEAR'), ('GROCERY', 'GROCERY'), ('ELECTRONICS', 'ELECTRONICS'), ('STATIONERY', 'STATIONERY')], default='', max_length=50),
        ),
    ]
