# Generated by Django 3.2.12 on 2023-07-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Shipped', 'Order Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default=('Order Placed', 'Order Placed'), max_length=20)),
                ('timeStamp', models.DateField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
